python plot_seismic_data_all_channels.py configurations/plot_independent_channels_geophone_1.yaml
python plot_seismic_data_all_channels.py configurations/plot_independent_channels_geophone_2.yaml
python plot_seismic_data_all_channels.py configurations/plot_independent_channels_geophone_3.yaml
python plot_seismic_data_all_channels.py configurations/plot_independent_channels_geophone_4.yaml
python plot_seismic_data_all_channels.py configurations/plot_independent_channels_geophone_5.yaml
python plot_seismic_data_all_channels.py configurations/plot_independent_channels_geophone_6.yaml
python plot_seismic_data_all_channels.py configurations/plot_independent_channels_geophone_7.yaml
python plot_seismic_data_all_channels.py configurations/plot_independent_channels_geophone_8.yaml

